plugins:
  - rubocop-rake
  - rubocop-rspec

inherit_from:
  - https://raw.githubusercontent.com/bsm/misc/refs/heads/main/rubocop/default.yml
  - https://raw.githubusercontent.com/bsm/misc/refs/heads/main/rubocop/rspec.yml

inherit_mode:
  merge:
    - Exclude
