matrix:
  include:
    - language: ruby
      rvm:
        - 2.7
      before_install:
        - wget https://apache.bintray.com/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-archive-keyring-latest-$(lsb_release --codename --short).deb
        - sudo apt install -y ./apache-arrow-archive-keyring-latest-$(lsb_release --codename --short).deb
        - sudo apt update
        - sudo apt install -y libarrow-dev libarrow-glib-dev libarrow-dataset-dev libplasma-dev libplasma-glib-dev libgandiva-dev libgandiva-glib-dev libparquet-dev libparquet-glib-dev
    - language: ruby
      rvm:
        - 2.6
      before_install:
        - wget https://apache.bintray.com/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-archive-keyring-latest-$(lsb_release --codename --short).deb
        - sudo apt install -y ./apache-arrow-archive-keyring-latest-$(lsb_release --codename --short).deb
        - sudo apt update
        - sudo apt install -y libarrow-dev libarrow-glib-dev libarrow-dataset-dev libplasma-dev libplasma-glib-dev libgandiva-dev libgandiva-glib-dev libparquet-dev libparquet-glib-dev
    - language: go
      go:
        - 1.14.x
    - language: go
      go:
        - 1.13.x
