// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.11.3
// source: internal/testdata/testdata.proto

package testdata

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MockEnum int32

const (
	MockEnum_UNKNOWN MockEnum = 0
	MockEnum_FIRST   MockEnum = 3
)

// Enum value maps for MockEnum.
var (
	MockEnum_name = map[int32]string{
		0: "UNKNOWN",
		3: "FIRST",
	}
	MockEnum_value = map[string]int32{
		"UNKNOWN": 0,
		"FIRST":   3,
	}
)

func (x MockEnum) Enum() *MockEnum {
	p := new(MockEnum)
	*p = x
	return p
}

func (x MockEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MockEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_testdata_testdata_proto_enumTypes[0].Descriptor()
}

func (MockEnum) Type() protoreflect.EnumType {
	return &file_internal_testdata_testdata_proto_enumTypes[0]
}

func (x MockEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MockEnum.Descriptor instead.
func (MockEnum) EnumDescriptor() ([]byte, []int) {
	return file_internal_testdata_testdata_proto_rawDescGZIP(), []int{0}
}

type MockMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enum   MockEnum `protobuf:"varint,2,opt,name=enum,proto3,enum=feedx.internal.testdata.MockEnum" json:"enum,omitempty"`
	Height uint32   `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *MockMessage) Reset() {
	*x = MockMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_testdata_testdata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MockMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockMessage) ProtoMessage() {}

func (x *MockMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testdata_testdata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockMessage.ProtoReflect.Descriptor instead.
func (*MockMessage) Descriptor() ([]byte, []int) {
	return file_internal_testdata_testdata_proto_rawDescGZIP(), []int{0}
}

func (x *MockMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MockMessage) GetEnum() MockEnum {
	if x != nil {
		return x.Enum
	}
	return MockEnum_UNKNOWN
}

func (x *MockMessage) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_internal_testdata_testdata_proto protoreflect.FileDescriptor

var file_internal_testdata_testdata_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64,
	0x61, 0x74, 0x61, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x17, 0x66, 0x65, 0x65, 0x64, 0x78, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x22, 0x70, 0x0a, 0x0b, 0x4d,
	0x6f, 0x63, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x35,
	0x0a, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x66,
	0x65, 0x65, 0x64, 0x78, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4d, 0x6f, 0x63, 0x6b, 0x45, 0x6e, 0x75, 0x6d, 0x52,
	0x04, 0x65, 0x6e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x2a, 0x22, 0x0a,
	0x08, 0x4d, 0x6f, 0x63, 0x6b, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x49, 0x52, 0x53, 0x54, 0x10,
	0x03, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x66, 0x65, 0x65, 0x64, 0x78, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74,
	0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_testdata_testdata_proto_rawDescOnce sync.Once
	file_internal_testdata_testdata_proto_rawDescData = file_internal_testdata_testdata_proto_rawDesc
)

func file_internal_testdata_testdata_proto_rawDescGZIP() []byte {
	file_internal_testdata_testdata_proto_rawDescOnce.Do(func() {
		file_internal_testdata_testdata_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_testdata_testdata_proto_rawDescData)
	})
	return file_internal_testdata_testdata_proto_rawDescData
}

var file_internal_testdata_testdata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_testdata_testdata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_testdata_testdata_proto_goTypes = []interface{}{
	(MockEnum)(0),       // 0: feedx.internal.testdata.MockEnum
	(*MockMessage)(nil), // 1: feedx.internal.testdata.MockMessage
}
var file_internal_testdata_testdata_proto_depIdxs = []int32{
	0, // 0: feedx.internal.testdata.MockMessage.enum:type_name -> feedx.internal.testdata.MockEnum
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_testdata_testdata_proto_init() }
func file_internal_testdata_testdata_proto_init() {
	if File_internal_testdata_testdata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_testdata_testdata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MockMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_testdata_testdata_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_testdata_testdata_proto_goTypes,
		DependencyIndexes: file_internal_testdata_testdata_proto_depIdxs,
		EnumInfos:         file_internal_testdata_testdata_proto_enumTypes,
		MessageInfos:      file_internal_testdata_testdata_proto_msgTypes,
	}.Build()
	File_internal_testdata_testdata_proto = out.File
	file_internal_testdata_testdata_proto_rawDesc = nil
	file_internal_testdata_testdata_proto_goTypes = nil
	file_internal_testdata_testdata_proto_depIdxs = nil
}
